baseurl = "/"
title = "Jon Durbin's Playground"
author = "Jonathan Durbin"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Jon's Playground"

[[menu.main]]
    name = "Home"
    url = "https://nanx.me"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/jonathan-durbin/my_site"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jonathan-durbin-houghton/"
    weight = 3
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
