baseurl = "https://jonathan-durbin.rbind.io/"
title = "Jon"
author = "Jonathan Durbin"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Just Jon"

[[menu.main]]
    name = "This Site's GitHub"
    url = "https://github.com/jonathan-durbin/my_site"
    weight = 1
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jonathan-durbin-houghton/"
    weight = 2
[[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight = 3
